import { useState } from "react";
import { useNavigate } from "react-router-dom";

import { preview } from "../assets";
import { getRandomPrompt } from "../utils";
import { FormField, Loader } from "../components";

const CreatePost = () => {
	const navigate = useNavigate();
	const [form, setForm] = useState({
		name: "",
		prompt: "",
		photo: "",
	});
	const [generatingImg, setGeneratingImg] = useState(false);
	const [loading, setLoading] = useState(false);

	const generateImage = () => {};

	const handleSubmit = () => {};

	const handleChange = () => {};

	const handleSurpriseMe = () => {};

	return (
		<section className="max-w-7xl mx-auto">
			<div>
				<h1 className="font-extrabold blacktext text-[32px]">Create</h1>
				<p className="mt-2 graytext text-[16px] max-w-[600px]">
					Create imaginative and visually stunning images generated by DALL-E AI
					and share them with the community
				</p>
			</div>
			<form className="mt-16 max-w-3xl" onSubmit={handleSubmit}>
				<div className="flex flex-col gap-5">
					<FormField
						labelName="Your name"
						type="text"
						name="name"
						placeholder="Alex Pushkin"
						value={form.name}
						handleChange={handleChange}
					/>
					<FormField
						labelName="Prompt"
						type="text"
						name="prompt"
						placeholder="A futuristic cyborg dance club, neon lights"
						value={form.prompt}
						handleChange={handleChange}
						isSupriseMe
						handleSurpriseMe={handleSurpriseMe}
					/>
					<div className="relative bg-gray-50 border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 w-64 p-3 h-64 flex justify-center items-center">
						{form.photo ? (
							<img
								src={form.photo}
								alt={form.prompt}
								className="w-full h-full object-contain"
							/>
						) : (
							<img
								src={preview}
								alt="preview"
								className="w-9/12 h-9/12 object-contain opacity-40"
							/>
						)}
						{generatingImg && (
							<div className="absolute inset-0 z-0 flex justify-center items-center bg-[rgba(0,0,0,0.5)] rounded-lg">
								<Loader />
							</div>
						)}
					</div>
				</div>

				<div className="mt-5 flex gap-5">
					<button
						type="button"
						onClick={generateImage}
						className="text-white bg-[#4a4fd9] font-medium rounded-xl text-sm w-full sm:w-auto px-5 py-3 text-center"
					>
						{generatingImg ? "Generating..." : (<span>Generate &#129302;</span>)}
					</button>
				</div>

        <div className="mt-10">
          <p className="mt-2 text-[#666e75] text-[14px]">Once you have created the image you want, you can share it with others in the community</p>
          <button type='submit' className="mt-3 text-white bg-green-600 font-medium rounded-xl text-sm w-full sm:w-auto px-5 py-2.5 text-center">Share with the community</button>
        </div>
			</form>
		</section>
	);
};

export default CreatePost;
